# ==============================================================================
# Engine Configuration File
# ==============================================================================

[paths]
shader_dir = "shaders/"
asset_dir = "assets/"
scene_dir = "assets/scenes/"

[window]
title = "abra"
width = 0
height = 0
fullscreen = false

[hdr]
enabled = false

[msaa]
enabled = false
samples = 4

[camera]
yaw = -90.0
pitch = 0.0
speed = 10.0
sensitivity = 0.1
zoom = 45.0
znear = 0.1
zfar = 100000.0
[camera.ubo]
binding = 0
blockName = "CameraBlock"

[lights]
max_directional = 1
max_point = 4
max_spot = 4
[light.ubo]
binding = 1
blockName = "LightBlock"

[shadow.map]
width = 1024
height = 1024
slot = 6
[shadow.ubo]
binding = 2
blockName = "ShadowBlock"
[shadow.directional]
height = 5.0
near = 1.0
far = 7.5
left = -10.0
right = 10.0
bottom = -10.0
top = 10.0
[shadow.omnidirectional]
near = 1.0
far = 25.0
fovy = 90.0
[shadow.perspective]
near = 1.0
far = 25.0

[ssao]
kernel_size = 16
radius = 0.5
bias = 0.025
intensity = 3.0
slot = 12
[ssao.ubo]
binding = 3
blockName = "SSAOBlock"
[ssao.noise]
size = 4
slot = 18

[pbr]
envmap_size = 512
irradiance_map_size = 32
prefilter_map_size = 128
brdf_lut_size = 512

[pbr.texture_slots]
albedo = 0
normal = 1
rm = 2
ao = 3
emissive = 4
height = 5
irradiance_map = 9
prefilter_map = 10
brdf_lut = 11

[gbuffer.indices]
position = 0
normal = 1
albedo = 2
orm = 3
depth = 4

[gbuffer.texture_slots]
position = 13
normal = 14
albedo = 15
orm = 16
depth = 17